// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNhNP-GJtn-ZDtM0vdJBBlqg9CzZAMLHk',
    appId: '1:765801575548:web:a498be115b966761df45f9',
    messagingSenderId: '765801575548',
    projectId: 'mdii-c4ae3',
    authDomain: 'mdii-c4ae3.firebaseapp.com',
    storageBucket: 'mdii-c4ae3.firebasestorage.app',
    measurementId: 'G-VXBME02MZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOq8ScpyJ4b5qQr2RpiaxLGV-xLpPl8LY',
    appId: '1:765801575548:android:831fc83de297e108df45f9',
    messagingSenderId: '765801575548',
    projectId: 'mdii-c4ae3',
    storageBucket: 'mdii-c4ae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFd7X9Ic7KSyEhTsOcrzCRy5-y3AdnsPY',
    appId: '1:765801575548:ios:f9e273fc78d73af5df45f9',
    messagingSenderId: '765801575548',
    projectId: 'mdii-c4ae3',
    storageBucket: 'mdii-c4ae3.firebasestorage.app',
    iosBundleId: 'com.example.bitshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFd7X9Ic7KSyEhTsOcrzCRy5-y3AdnsPY',
    appId: '1:765801575548:ios:f9e273fc78d73af5df45f9',
    messagingSenderId: '765801575548',
    projectId: 'mdii-c4ae3',
    storageBucket: 'mdii-c4ae3.firebasestorage.app',
    iosBundleId: 'com.example.bitshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNhNP-GJtn-ZDtM0vdJBBlqg9CzZAMLHk',
    appId: '1:765801575548:web:9210d88d00668c36df45f9',
    messagingSenderId: '765801575548',
    projectId: 'mdii-c4ae3',
    authDomain: 'mdii-c4ae3.firebaseapp.com',
    storageBucket: 'mdii-c4ae3.firebasestorage.app',
    measurementId: 'G-5H0ND63DJP',
  );
}
